package com.learning.sandwich.sandy.model;

/*
    Copyright 2019 Jeff Franken
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import java.io.Serializable;

/**
 * This class is sad and lonely. It will include the attributes and accessors of of te response
 * entity, which are now stored as string resourcs
 */
@Entity
public class Response implements Serializable {

  private static final long serialVersionUID = 1L;


  @ColumnInfo(name = "response_id")
  @PrimaryKey
  private long responseId;

  @ColumnInfo(name = "response_category")
  private int responseCategory;

  /**
   * @param sandySpeaks This should never be used to genertae sandy's response, but code won;t
   * compile without it
   */
  public void setSandySpeaks(String sandySpeaks) {
    this.sandySpeaks = sandySpeaks;
  }

  @ColumnInfo(name = "sandy_speaks")
  private String sandySpeaks;

  /**
   * @return This method will gt the response id, which will be autogenerated by Room
   */
  public long getResponseId() {
    return responseId;
  }


  /**
   * @return this method gets the response category (is sandwich, is not, Sandy and human differ)
   */
  public int getResponseCategory() {
    return responseCategory;
  }

  /**
   * @param responseCategory thismethod sets the response category
   */
  public void setResponseCategory(int responseCategory) {
    this.responseCategory = responseCategory;
  }

  /**
   * @return This will get the string containing the rxt a user will see as the response
   */
  public String getSandySpeaks() {
    return sandySpeaks;
  }

  /**
   * @param responseId This should never be used to set response ID but code won't compile without it
   */
  public void setResponseId(long responseId) {
    this.responseId = responseId;
  }


}
